### ISSUE TITLE
Error "googleServiceAccountJsonPath config must be defined" in demo mode

### ISSUE THREAD

**Issue by ronakg** [google-pay/pass-converter#15]
Hi,

I'm running the converter locally on my mac and when I try to convert a `.pkpass` file, I get this error. From what I understand, running the app locally like this shouldn't need the `googleServiceAccountJsonPath`.

Am I missing something?

Log -

```
$ node app.js demo
Listening on http://undefined:3000
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Cannot convert to Google Wallet pass, googleServiceAccountJsonPath config must be defined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v20.1.0
```

**Comment by stephenmcd** [comment]
Hi, please see the External Dependencies section in the readme which covers this - you need a Google Cloud service account JSON file to either authenticate with the Wallet API, or sign the pass JWT, depending on which method is used.
