### ISSUE TITLE
Apple Pass requires Dev Account?

### ISSUE THREAD

**Issue by MentalGear** [google-pay/pass-converter#5]
I was just wondering whether when converting a google pass to an apple pass, if there's also an Apple Dev Account and certificate required?

Can Google Passes also be used on Apple devices with another app?

**Comment by stephenmcd** [comment]
Hi there,

I can't comment on what Apple devices support, you'll need to consult Apple documentation for that.

As for Apple certificates when converting, you can convert Google to Apple passes without a certificate, but the resulting pass will not be signed, and you'll need to programatically do that yourself separately. This is covered in detail in the README, so please consult it for clarity.
