### ISSUE TITLE
Local certificate issue while trying to install the dependencies

### ISSUE THREAD

**Issue by Viper-ui** [google-pay/pass-converter#8]
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! errno UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! request to https://github.com/node-apn/node-http2/archive/apn-2.1.4.tar.gz failed, reason: unable to get local issuer certificate
 
Because of the above issues i am unable to run the conversion demo the test the command line conversion technique.

**Comment by stephenmcd** [comment]
The error is coming from the node-apn dependency (presumably you haven't configured it, which is covered in the readme), however other than being imported, any use of node-apn only occurs when the converter is run as a web service (either in demo mode, or not), so I'm unsure how you've caused that error to occur. Are you sure you've only tried to convert a local pass via command line? If so, it may be worth seeking support via the node-apn project, since it would then appear to be unrelated to this project.

**Comment by Viper-ui** [comment]
No I didn't even get a chance to test the command line conversion technique as while hitting the npm i command itself i am getting this error.
what should be done in that case?

And which part in the readme are you referring where the node-apn depency config are given?

**Comment by stephenmcd** [comment]
I was incorrect about this being a node-apn issue, it's actually an issue with npm itself and your environment, and is entirely unrelated to this project. If you google the error message you'll find a lot of information - here are a couple of results that look useful:

https://stackoverflow.com/questions/45884752/npm-err-code-unable-to-get-issuer-cert-locally
https://stackoverflow.com/questions/72444102/cannot-load-a-package-using-npm-local-certificate-error

I'll close this for now, but please re-open if I've misunderstood something.

**Comment by Viper-ui** [comment]
I was able to solve the npm issue but now while running the command line conversion technique i am getting the below error:
Cannot determine public host for image image-_z4wkZ9p2mZ8ioSeEffT_.png as googleStorageBucket config is not defined. The resulting pass will not be savable to Google Wallet without adding the URL for this image.

command ran: node app.js "C:\Users\viper\Downloads\DBC (1).pkpass" "C:\Users\viper\Desktop\gg.json"

**Comment by Viper-ui** [comment]
@stephenmcd The warning which we get states that we need google storage bucket config does that mean we need the config for command line as well and by adding the URL for the image what exactly do you mean as to where do we have to provide that because I am not able to get any converted pass in my output path which I am providing in the command line tools.

**Comment by stephenmcd** [comment]
You can still create Google passes locally with the command line tool, but without some form of hosting the images, the passes will not be usable.
