### ISSUE TITLE
Error after uploading the file in the converter

### ISSUE THREAD

**Issue by Viper-ui** [google-pay/pass-converter#9]
As soon as we are uploading the file getting the below error..
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Cannot convert to Google Wallet pass, googleServiceAccountJsonPath config must be defined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

**Comment by stephenmcd** [comment]
The error states what you need to do - "Cannot convert to Google Wallet pass, googleServiceAccountJsonPath config must be defined". If this needs further clarification, please go through the README file which covers everything in detail.

If I've overlooked something, feel free to re-open this.
